/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Evict the Typst memoization cache.
 *
 * Typst uses a process-global memoization cache (comemo) for incremental
 * compilation. When mdpdf is used in a long-running process, this cache
 * grows unboundedly because each call creates a fresh MdpdfWorld, so cached
 * entries from previous compilations are never reused but never freed either.
 *
 * Call this function periodically (e.g. after each `markdownToPdf` call) to
 * reclaim native memory. Pass `maxAge = 0` to clear the entire cache, or a
 * higher value to retain recently-used entries.
 */
export declare function evict(maxAge: number): void;

export declare function markdownToPdf(
  markdown: string,
  typstConfig?: string | undefined | null,
  toc?: boolean | undefined | null,
): Promise<Buffer>;

export declare function markdownToTypstCode(
  markdown: string,
  typstConfig?: string | undefined | null,
  toc?: boolean | undefined | null,
): Promise<string>;
